### ISSUE TITLE
Sample code: Player Points & Recent Activities

### ISSUE THREAD

**Issue by rysull23** [cwendt94/espn-api#133]
As I mentioned in my other [recent post about free agents](https://github.com/cwendt94/espn-api/issues/127), last year I created a local copy and made some additions. Dusting it off for this season and just came across this set of code. Thought you might like to see it. Ultimately, I think the most valuable aspect of this is the ability to go from: string to Player Object to Player Points. Is there any other way to hit the api with a string and return the respective players points week-over-week? Let me know if you have any questions on all this and feel free to incorporate as you'd like. Would also love to know if there's a better way to go about what I did. Thanks!

**Sample Outcome**:

- recent_activity returns actions where player is not a string, but a Player Object
- The player Object includes a points attribute which is derived from a fetch_player_points method
- player.points shows current week points and last week points (there's probably more to unpack here)

![image](https://user-images.githubusercontent.com/31132172/94488958-9e345100-01b1-11eb-9a50-4d8adcafbd51.png)

**Activity Class**: includes a Player Object in `actions`, where Player includes `points` as derived from `fetch_player_points`

```
class Activity(object):
    def __init__(self, data, player_map, get_team_data, get_player_data, fetch_player_points):
        self.actions = []  # List of tuples (Team, action, player)
        for msg in data['messages']:
            team = ''
            action = 'UNKNOWN'
            player = ''
            msg_id = msg['messageTypeId']
            if msg_id == 244:
                team = get_team_data(msg['from'])
            elif msg_id == 239:
                team = get_team_data(msg['for'])
            else:
                team = get_team_data(msg['to'])
            if msg_id in ACTIVITY_MAP:
                action = ACTIVITY_MAP[msg_id]
            if msg['targetId'] in player_map:
                player = player_map[msg['targetId']]
            self.date = msg['date']
            player = Player(get_player_data(msg['targetId']),fetch_player_points)
            self.actions.append((team, action, player))

    def __repr__(self):
        return 'Activity(' + ' '.join("(%s,%s,%s)" % tup for tup in self.actions) + ')'
```

**Player Class: fetch_player_points** as seen in Sample outcome

```
def fetch_player_points(self, playerId: int):
        """Retrieves a player's points"""

        params = {
            'scoringPeriodId': 5,
            'view': 'kona_player_info',

        }
        filters = {"players": {
            "filterIds": {"value": [playerId]},
            "sortPercOwned": {"sortPriority": 2, "sortAsc": False},
            "filterStatsForTopScoringPeriodIds": {"value": 3,
                                                  "additionalValue": ["002019", "102019", "002018", "1120195",
                                                                      "022019"]}}}
        headers = {'x-fantasy-filter': json.dumps(filters)}
        r = requests.get(self.ENDPOINT, params=params, cookies=self.cookies, headers=headers)
        data = r.json()

        stats = data['players'][0]['player']['stats']
        player_points = {}
        for stat in stats:

            if stat['id'] == str('00') + str(self.year):
                player_points['points_season_total'] = stat['appliedTotal']
                player_points['points_season_average'] = stat['appliedAverage']
            if stat['id'] == str('00') + str(self.year-1):
                player_points['points_season_last'] = stat['appliedTotal']
            if stat['scoringPeriodId'] == self.current_week:
                player_points['points_week_current'] = stat['appliedTotal']
            if stat['scoringPeriodId'] == self.current_week - 1:
                player_points['points_week_last'] = stat['appliedTotal']

        return player_points
```

```
class Player(object):
    """Player are part of team"""

    def __init__(self, data, fetch_player_points):
        self.name = json_parsing(data, 'fullName')
        self.playerId = json_parsing(data, 'id')
        self.posRank = json_parsing(data, 'positionalRanking')
        self.eligibleSlots = [POSITION_MAP[pos] for pos in json_parsing(data, 'eligibleSlots')]
        self.acquisitionType = json_parsing(data, 'acquisitionType')
        self.proTeam = PRO_TEAM_MAP[json_parsing(data, 'proTeamId')]
        self.positionalRanking = json_parsing(data, 'positionalRanking')
        self.totalRanking = json_parsing(data, 'totalRanking')
        self.totalRating = json_parsing(data, 'totalRating')

        self.fetch_player_points = fetch_player_points
        # Get player's season points
        self.points = fetch_player_points(self.playerId)
```

**League Class:**

**recent_activity**
`activity = [Activity(topic, self.player_map, self.get_team_data,self.get_player_data,self.fetch_player_points) for topic in data]`

```
def get_player_data(self, playerId: int):
        """Retrieves a player data from api"""

        params = {
            'scoringPeriodId': 5,
            'view': 'kona_player_info',

        }
        filters = {"players": {
            "filterIds": {"value": [playerId]},
            "sortPercOwned": {"sortPriority": 2, "sortAsc": False},
            "filterStatsForTopScoringPeriodIds": {"value": 3,
                                                  "additionalValue": ["002019", "102019", "002018", "1120195",
                                                                      "022019"]}}}
        headers = {'x-fantasy-filter': json.dumps(filters)}
        r = requests.get(self.ENDPOINT, params=params, cookies=self.cookies, headers=headers)
        data = r.json()['players'][0]['player']

        return data
```

**Comment by cwendt94** [comment]
This is great, thanks for posting your updates! I will definitely look into adding player object to `recent_activity` and see what data can be pulled!

**Comment by glennrfriedman** [comment]
@rysull23 I just asked a very similar question in another issue; trying to get the total player points for the season. 

Would it be possible for you to share the full player.py?

**Comment by glennrfriedman** [comment]
Currently seeing the following error which I think is basically related to me not knowing exactly where to place the fetch_player_points def 

```
Traceback (most recent call last):
  File "espn_ff.py", line 12, in <module>
    league = League(league_id=league_id, year=year, espn_s2=espn_s2, swid=swid)
  File "/usr/local/lib/python3.8/site-packages/espn_api/football/league.py", line 21, in __init__
    self._fetch_league()
  File "/usr/local/lib/python3.8/site-packages/espn_api/football/league.py", line 28, in _fetch_league
    self._fetch_teams(data)
  File "/usr/local/lib/python3.8/site-packages/espn_api/football/league.py", line 33, in _fetch_teams
    super()._fetch_teams(data, TeamClass=Team)
  File "/usr/local/lib/python3.8/site-packages/espn_api/base_league.py", line 63, in _fetch_teams
    self.teams.append(TeamClass(team, roster=roster, member=member, schedule=schedule))
  File "/usr/local/lib/python3.8/site-packages/espn_api/football/team.py", line 33, in __init__
    self._fetch_roster(roster)
  File "/usr/local/lib/python3.8/site-packages/espn_api/football/team.py", line 44, in _fetch_roster
    self.roster.append(Player(player))
TypeError: __init__() missing 1 required positional argument: 'fetch_player_points'
```

**Comment by cwendt94** [comment]
In the latest package (0.8.0) I added `total_points` and `projected_total_points` to Player Class and now `recent_activity` returns Player Object instead of string

**Comment by rysull23** [comment]
Hey @glennrfriedman - Looks like I stuck the fetch_player_points method as a required input variable into the Player Object __init__ function. You can see below, for example, that in the get_free_agents call, the method is passed into the Player object. It would also seem I stuck it into get_teams and get_roster in the Team object...I seem to have forced it in all over the place!

Let's see how @cwendt94 added this, as I'm sure he found a far more elegant way. Thanks for adding! Super cool. Any luck with the other stats, like last_week_points, etc? It was a bit cryptic but seemed to be a lot of stats you can extract.

```
from .constant import POSITION_MAP, PRO_TEAM_MAP
from .utils import json_parsing
from .tiers import PLAYER_TIER_MAP
from .league import requests, json


class Player(object):
    """Player are part of team"""

    def __init__(self, data, fetch_player_points):
        self.name = json_parsing(data, 'fullName')
        self.playerId = json_parsing(data, 'id')
        self.posRank = json_parsing(data, 'positionalRanking')
        self.eligibleSlots = [POSITION_MAP[pos] for pos in json_parsing(data, 'eligibleSlots')]
        self.acquisitionType = json_parsing(data, 'acquisitionType')
        self.proTeam = PRO_TEAM_MAP[json_parsing(data, 'proTeamId')]
        self.positionalRanking = json_parsing(data, 'positionalRanking')
        self.totalRanking = json_parsing(data, 'totalRanking')
        self.totalRating = json_parsing(data, 'totalRating')

        self.fetch_player_points = fetch_player_points

        # Get players main position
        for pos in json_parsing(data, 'eligibleSlots'):
            if (pos != 25 and '/' not in POSITION_MAP[pos]) or '/' in self.name:
                self.position = POSITION_MAP[pos]
                break
       
        # Get player's season points
        self.points = fetch_player_points(self.playerId)

    def __repr__(self):
        return 'Player(%s|%s)' % (self.name, self.position)
```

```
def get_free_agents(self, week: int=None, size: int=50, position: str=None) -> List[Player]:
        """Returns a List of Free Agents for a Given Week"""

        if self.year < 2018:
            raise Exception('Cant use free agents before 2018')
        if not week:
            week = self.current_week

        slot_filter = []
        if position and position in POSITION_MAP:
            slot_filter = [POSITION_MAP[position]]

        params = {
            'view': 'kona_player_info',
            'scoringPeriodId': week,
        }
        filters = {"players":{"filterStatus":{"value":["FREEAGENT","WAIVERS"]},"filterSlotIds":{"value":slot_filter},"limit":size,"sortPercOwned":{"sortPriority":1,"sortAsc":False},"sortDraftRanks":{"sortPriority":100,"sortAsc":True,"value":"STANDARD"}}}
        headers = {'x-fantasy-filter': json.dumps(filters)}

        r = requests.get(self.ENDPOINT, params=params, cookies=self.cookies, headers=headers)
        self.status = r.status_code
        checkRequestStatus(self.status)

        players = r.json()['players']

        return [Player(player,self.fetch_player_points) for player in players]
```

```
def _fetch_teams(self):
        """Fetch teams in league"""

        ...

        for team in teams:
            for member in members:
                # For league that is not full the team will not have a owner field
                if 'owners' not in team or not team['owners']:
                    member = None
                    break
                elif member['id'] == team['owners'][0]:
                    break
            roster = team_roster[team['id']]
            self.teams.append(Team(team, roster, member, schedule,self.fetch_player_points))

       ...

```


```
class Team(object):
    """Teams are part of the league"""
    def __init__(self, data, roster, member, schedule,fetch_player_points):

    def _fetch_roster(self, data):
        '''Fetch teams roster'''
        self.roster.clear()
        roster = data['entries']

        for player in roster:
            self.roster.append(Player(player, self.fetch_player_points))
```

**Comment by cwendt94** [comment]
I like the idea of adding `totalRanking` and `totalRating` to the player class as well. The last week points can be found in the `stats` field for the Player. I was thinking keeping week points general and just having it be keyed in the `stats` dict or can always get box scores for a specific week. So you can always do something like
```python
stats = league.teams[0].roster[0].stats
stats[league.current_week - 1]
# or
box_scores = league.box_scores(week=2)
```

One other field I was thinking of adding to the Player class and might be useful is having `last_year_points` and `last_year_projected_points`. I will have to double check but I believe those values are usually always in the API data returned.
