### ISSUE TITLE
"Access Denied" trying to get recent activity

### ISSUE THREAD

**Issue by tburge260** [cwendt94/espn-api#245]
### Sport

Football

### Summary

When trying to call recenty_activity() receiving a Acess Denied exception

### Logs/Data

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 20, in on_message
    activitys = league.recent_activity()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/espn_api/football/league.py", line 161, in recent_activity
    data = self.espn_request.league_get(extend='/communication/', params=params, headers=headers)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/espn_api/requests/espn_requests.py", line 39, in league_get
    checkRequestStatus(r.status_code)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/espn_api/requests/espn_requests.py", line 10, in checkRequestStatus
    raise Exception("Access Denied")
Exception: Access Denied

**Comment by tburge260** [comment]
Found in documentation needed access.
