### ISSUE TITLE
ESPN returned an HTTP 403

### ISSUE THREAD

**Issue by sweppner** [cwendt94/espn-api#586]
### Sport

Football

### Summary

This has been working great and I'm now getting the following error:

espn_api.requests.espn_requests.ESPNUnknownError: ESPN returned an HTTP 403

I've confirmed that I have the correct espn keys etc... What am I missing? 

I went back to basics to try and just use the simple example:

```
print("league")

league = League(
            league_id=test_league["league_id"],
            year=test_league["year"],
            espn_s2=test_league["espn_s2"],
            swid=test_league["swid"]
        )
print(league)

```
...but I'm still getting the same error. Can anyone confirm that this API is still working?

### Logs/Data

Traceback (most recent call last):
  File ".../core2/test.py", line 19, in <module>
    league = League(
  File ".../venv/lib/python3.9/site-packages/espn_api/football/league.py", line 24, in __init__
    self.fetch_league()
  File ".../venv/lib/python3.9/site-packages/espn_api/football/league.py", line 27, in fetch_league
    self._fetch_league()
  File ".../venv/lib/python3.9/site-packages/espn_api/football/league.py", line 30, in _fetch_league
    data = super()._fetch_league(SettingsClass=Settings)
  File ".../venv/lib/python3.9/site-packages/espn_api/base_league.py", line 30, in _fetch_league
    data = self.espn_request.get_league()
  File ".../venv/lib/python3.9/site-packages/espn_api/requests/espn_requests.py", line 75, in get_league
    data = self.league_get(params=params)
  File ".../venv/lib/python3.9/site-packages/espn_api/requests/espn_requests.py", line 55, in league_get
    checkRequestStatus(r.status_code, cookies=self.cookies, league_id=self.league_id)
  File ".../venv/lib/python3.9/site-packages/espn_api/requests/espn_requests.py", line 32, in checkRequestStatus
    raise ESPNUnknownError(f"ESPN returned an HTTP {status}")
espn_api.requests.espn_requests.ESPNUnknownError: ESPN returned an HTTP 403

**Comment by gporceng** [comment]
What was the solution here?
