### ISSUE TITLE
Key error when referencing matchup = 1

### ISSUE THREAD

**Issue by jwinik** [cwendt94/espn-api#592]
### Sport

Hockey

### Summary

When I try to pull week 1 matchup data, I get a keyerror that I can't trace. I tried doing period = 2 instead of period = 1 and it worked fine.

box_scores = league.box_scores(matchup_period=period)

Thanks in advance for the help!

### Logs/Data

`box_scores = league.box_scores(matchup_period=period)`
_Traceback (most recent call last):

  File "C:\Users\jwini\AppData\Local\Temp/ipykernel_29784/3928976037.py", line 1, in <module>
    box_scores = league.box_scores(matchup_period=period)

  File "C:\Users\jwini\anaconda3\lib\site-packages\espn_api\hockey\league.py", line 176, in box_scores
    box_data = [BoxScore(matchup, pro_schedule, matchup_total) for matchup in schedule]

  File "C:\Users\jwini\anaconda3\lib\site-packages\espn_api\hockey\league.py", line 176, in <listcomp>
    box_data = [BoxScore(matchup, pro_schedule, matchup_total) for matchup in schedule]

  File "C:\Users\jwini\anaconda3\lib\site-packages\espn_api\hockey\box_score.py", line 17, in __init__
    self.home_lineup = [BoxPlayer(player, pro_schedule) for player in home_roster.get('entries', [])]

  File "C:\Users\jwini\anaconda3\lib\site-packages\espn_api\hockey\box_score.py", line 17, in <listcomp>
    self.home_lineup = [BoxPlayer(player, pro_schedule) for player in home_roster.get('entries', [])]

  File "C:\Users\jwini\anaconda3\lib\site-packages\espn_api\hockey\box_player.py", line 24, in __init__
    self.pro_opponent = PRO_TEAM_MAP[opp_id]

KeyError: 129764_

**Comment by cwendt94** [comment]
Thanks for reporting! This is because of the new hockey team Utah Hockey Club. Need to add them in the pro team map.

**Comment by cwendt94** [comment]
fixed in v0.40.1!
