### ISSUE TITLE
Years 2018 and 2019 don't work

### ISSUE THREAD

**Issue by narry67** [cwendt94/espn-api#614]
### Sport

Football

### Summary

I am pulling from a private league. Years 2014-2017 and 2020-2024 work fine but when attempting to get 2018/2019 I get the error shown in the logs/data section. Any assistance would be appreciated.

### Logs/Data

/Users/username/Documents/PROJECT-NAME/.venv/bin/python /Users/username/Documents/PROJECT-NAME/API-ESPN.py 
Traceback (most recent call last):
  File "/Users/username/Documents/PROJECT-NAME/API-ESPN.py", line 16, in <module>
    league = League(league_id=286725, year=2019, espn_s2=s2_2018, swid=swid, debug=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Documents/PROJECT-NAME/.venv/lib/python3.12/site-packages/espn_api/football/league.py", line 32, in __init__
    self.fetch_league()
  File "/Users/username/Documents/PROJECT-NAME/.venv/lib/python3.12/site-packages/espn_api/football/league.py", line 35, in fetch_league
    self._fetch_league()
  File "/Users/username/Documents/PROJECT-NAME/.venv/lib/python3.12/site-packages/espn_api/football/league.py", line 38, in _fetch_league
    data = super()._fetch_league(SettingsClass=Settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Documents/PROJECT-NAME/.venv/lib/python3.12/site-packages/espn_api/base_league.py", line 32, in _fetch_league
    data = self.espn_request.get_league()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Documents/PROJECT-NAME/.venv/lib/python3.12/site-packages/espn_api/requests/espn_requests.py", line 75, in get_league
    data = self.league_get(params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Documents/PROJECT-NAME/.venv/lib/python3.12/site-packages/espn_api/requests/espn_requests.py", line 55, in league_get
    checkRequestStatus(r.status_code, cookies=self.cookies, league_id=self.league_id)
  File "/Users/username/Documents/PROJECT-NAME/.venv/lib/python3.12/site-packages/espn_api/requests/espn_requests.py", line 26, in checkRequestStatus
    raise ESPNAccessDenied(f"League {league_id} cannot be accessed with espn_s2={cookies.get('espn_s2')} and swid={cookies.get('SWID')}")
espn_api.requests.espn_requests.ESPNAccessDenied: League 286725 cannot be accessed with espn_s2=YOUR_ESPNS2_PLACEHOLDER and swid={YOUR_SWID_PLACEHOLDER}

Process finished with exit code 1

**Comment by narry67** [comment]
Apparently my league mates have access to it. I have no idea what I did different those years :(

**Comment by cwendt94** [comment]
That is really weird, so seems like a bug on ESPN's side. I wonder if there are any settings the commissioner can update or check out?

**Comment by narry67** [comment]
I am not sure but I can just use one of their cookies for the moment so the issue shouldn’t affect me anymore. I appreciate you all taking the time to help.

**Comment by cwendt94** [comment]
No problem, glad you are able to use a work around!
